name: "Assign Asana Task"
description: "Assigns an existing Asana task to a user based on PR assignment"
author: "Taimur Salman"
inputs:
  token:
    description: "Asana Personal Access Token"
    required: true
  pr-url:
    description: "Pull Request URL"
    required: true
  projectId:
    description: "Asana project GID"
    required: true
  assignee-email:
    description: "Email of person to assign task to"
    required: true
  github-user:
    description: "GitHub username of PR assignee"
    required: false

outputs:
  assigned:
    description: "Whether the task was successfully assigned"
  assignee:
    description: "Name of the assigned user"

runs:
  using: "node20"
  main: "./index.js"
