name: "Create Asana Task"
description: "Creates a new task in Asana"
author: "Taimur Salman"
inputs:
  token:
    description: "Asana Personal Access Token"
    required: true
  title:
    description: "Task title"
    required: true
  notes:
    description: "Task notes"
    required: false
  projectId:
    description: "Asana project GID"
    required: true
  assignee-email:
    description: "Email of person to assign task to"
    required: false
  github-user:
    description: "GitHub username of PR author"
    required: false

runs:
  using: "node20"
  main: "prod/index.js"
