name: "Create Asana Task"
description: "Creates a new task in Asana"
author: "Taimur Salman"
inputs:
  token:
    description: "Asana Personal Access Token"
    required: true
  title:
    description: "Task title"
    required: true
  notes:
    description: "Task notes"
    required: false
  projectId:
    description: "Asana project GID"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
