name: Assign Asana Task on Review Request

on:
  pull_request:
    types: [review_requested]

jobs:
  assign-asana-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get reviewer email
        id: get-reviewer-email
        run: |
          # Get the requested reviewer's login (excluding copilot)
          reviewer_login="${{ github.event.requested_reviewer.login }}"
          echo "reviewer_login=$reviewer_login" >> $GITHUB_OUTPUT
          
          # Skip if reviewer is copilot or if no reviewer was requested
          if [[ "$reviewer_login" == *"copilot"* ]] || [[ -z "$reviewer_login" ]]; then
            echo "Skipping assignment: reviewer is copilot or empty"
            echo "skip_assignment=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "skip_assignment=false" >> $GITHUB_OUTPUT
          
          # Get the reviewer's email using the Users API
          reviewer_email=$(gh api /users/$reviewer_login --jq '.email' 2>/dev/null || echo "")
          
          # If email is null or empty, try to get it from recent commits in the repo
          if [[ -z "$reviewer_email" || "$reviewer_email" == "null" ]]; then
            echo "Public email not available, searching commits..."
            # Get all commits and filter by author manually
            reviewer_email=$(gh api "/repos/${{ github.repository }}/commits?per_page=100" --jq --arg author "$reviewer_login" '.[] | select(.author.login == $author) | .commit.author.email' | head -1 || echo "")
          fi
          
          echo "reviewer_email=$reviewer_email" >> $GITHUB_OUTPUT
          echo "Found email for $reviewer_login: $reviewer_email"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign Asana Task
        if: steps.get-reviewer-email.outputs.skip_assignment == 'false'
        uses: ./.github/actions/assign-asana-task
        with:
          token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          pr-url: ${{ github.event.pull_request.html_url }}
          projectId: ${{ secrets.ASANA_PROJECT_ID }}
          assignee-email: ${{ steps.get-reviewer-email.outputs.reviewer_email }}
          github-user: ${{ steps.get-reviewer-email.outputs.reviewer_login }}
