name: Assign Asana Task on Review Request

on:
  pull_request:
    types: [review_requested]

jobs:
  assign-asana-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get reviewer email
        id: get-reviewer-email
        run: |
          # Get the requested reviewer's login (excluding copilot)
          reviewer_login="${{ github.event.requested_reviewer.login }}"
          echo "reviewer_login=$reviewer_login" >> $GITHUB_OUTPUT
          
          # Skip if reviewer is copilot or if no reviewer was requested
          if [[ "$reviewer_login" == *"copilot"* ]] || [[ -z "$reviewer_login" ]]; then
            echo "Skipping assignment: reviewer is copilot or empty"
            echo "skip_assignment=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "skip_assignment=false" >> $GITHUB_OUTPUT
          
          # Try to get email from recent commits by this user
          reviewer_email=$(gh api /repos/${{ github.repository }}/commits --author="$reviewer_login" --per-page=1 --jq '.[0].commit.author.email' || echo "")
          echo "reviewer_email=$reviewer_email" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign Asana Task
        if: steps.get-reviewer-email.outputs.skip_assignment == 'false'
        uses: ./.github/actions/assign-asana-task
        with:
          token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          pr-url: ${{ github.event.pull_request.html_url }}
          projectId: ${{ secrets.ASANA_PROJECT_ID }}
          assignee-email: ${{ steps.get-reviewer-email.outputs.reviewer_email }}
          github-user: ${{ steps.get-reviewer-email.outputs.reviewer_login }}
