name: Create Asana Task on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get PR author emails
        id: get-emails
        run: |
          commit_email=$(gh api /repos/${{ github.repository }}/pulls/${{ github.event.number }}/commits --jq '.[-1].commit.author.email')
          echo "commit_email=$commit_email" >> $GITHUB_OUTPUT

          # Get GitHub user login
          github_user="${{ github.event.pull_request.user.login }}"
          echo "github_user=$github_user" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Asana Task
        id: 'create_task'
        uses: ./.github/actions/create-asana-task
        with:
          token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          title: ${{ github.event.pull_request.title }}
          notes: "PR URL: ${{ github.event.pull_request.html_url }}"
          projectId: ${{ secrets.ASANA_PROJECT_ID }}
          assignee-email: ${{ steps.get-emails.outputs.commit_email }}
          github-user: ${{ steps.get-emails.outputs.github_user }}
      - name: 'Store task ID as label'
        run: |
          echo "task_id=${{ steps.create_task.outputs.task_id }}" >> $GITHUB_OUTPUT
          gh api repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
            --method POST \
            --field name="asana-task-${{ steps.create_task.outputs.task_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
