name: Create Asana Task on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  asana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: .github/actions/asana-task

      - name: Build Action with ncc
        run: npm run build
        working-directory: .github/actions/asana-task

      - name: Commit built dist/ if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
              
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/${{ github.repository }}
    
          git add dist/
          git diff --cached --quiet || git commit -m "Build dist output [skip ci]"
        working-directory: .github/actions/asana-task
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Asana Task Action
        uses: ./.github/actions/asana-task
        with:
          token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          title: ${{ github.event.pull_request.title }}
          notes: "PR URL: ${{ github.event.pull_request.html_url }}"
          projectId: ${{ secrets.ASANA_PROJECT_ID }}